[package]
name = "plugin-interface"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
wit-bindgen = "0.45.0"

[features]
default = []
host = []
guest = []
